server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  # SPA의 클라이언트 라우팅 지원
  location / {
    try_files $uri $uri/ /index.html;
  }

  # 캐시 정책 - 추후 적용 가능성 검토
  # location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
  #   try_files $uri =404;
  #   expires 1y;
  #   access_log off;
  #   add_header Cache-Control "public";
  # }
}