apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solra
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/fisa4th-final-project/solra-frontend
    newTag: 0e78fd674b1acb5b854822aeb654636b8b64be59

