apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: solra
resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: ghcr.io/fisa4th-final-project/solra-frontend
    newTag: 25b9fbf384bd043efa78153f76a3091aaf6bb83c

