apiVersion: apps/v1
kind: Deployment
metadata:
  name: solra-frontend

spec:
  template:
    spec:
      containers:
        - name: solra-frontend
          env:
            - name: VUE_PROFILES_ACTIVE
              value: dev
          envFrom:
            - configMapRef:
                name: dev-config-map
